# Generated by Django 5.2.1 on 2025-06-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Основной код региона (например, RF-1100)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Наименование региона', max_length=255)),
                ('country_id', models.IntegerField(help_text='ID страны (если используется для связи)')),
                ('okato_code', models.CharField(blank=True, help_text='Код ОКАТО/ОКТМО', max_length=20, null=True)),
                ('map_code', models.CharField(blank=True, help_text='Код региона как в geoJSON/картах AmCharts (например, RU-AD, RU-RF)', max_length=15, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'db_table': 'regions',
                'ordering': ['name'],
            },
        ),
    ]
