# Generated by Django 5.2.1 on 2025-06-03 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время запуска')),
                ('custom_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название прогноза (польз.)')),
                ('input_parameters_json', models.JSONField(verbose_name='Входные параметры (JSON)')),
                ('results_file_path', models.CharField(blank=True, max_length=512, null=True, verbose_name='Путь к файлу результатов (относительно MEDIA_ROOT)')),
                ('warnings_json', models.JSONField(blank=True, default=list, verbose_name='Предупреждения')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Запуск прогноза',
                'verbose_name_plural': 'Запуски прогнозов',
                'ordering': ['-created_at'],
            },
        ),
    ]
